spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
server.port=8081
spring.datasource.username=zeina
spring.datasource.password=zeina
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
